# server_url: https://<SPACE>.kinops.io  OR https://<SERVER_NAME>.com/kinetic/<SPACE_SLUG>
SERVER_URL: 
SPACE_USERNAME: 
SPACE_PASSWORD: 
SPACE_SLUG: 
KAPP_SLUG: 
#Empty value in "FORM_SLUG" for Kapp Query or provide a Form Slug for a Form Query
FORM_SLUG: 
# Empty Value for "TYPE" does not include a Type in the search.
TYPE: 
#Empty Value for "CORESTATE" or include a value of "Draft", "Submitted", or "Closed"
CORESTATE:  
#QUERY: values[Field One] = "value" AND values[Status]="active"
QUERY:
LIMIT: "100" #Limit of records to return (there is no pagination)
LOG_LEVEL: INFO # {OFF, INFO, or DEBUG}