# server_url: https://<SPACE>.kinops.io  OR https://<SERVER_NAME>.com/kinetic/<SPACE_SLUG>
SERVER_URL: 
SPACE_USERNAME: 
SPACE_PASSWORD: 
SPACE_SLUG: 
KAPP_SLUG: services
#FORM_SLUG: Empty value for Kapp Query or provide a Form Slug for a Form Query
FORM_SLUG: 
#QUERY: createdBy= "integration_user"
QUERY: 
#INCLUDE: Comma-separated list of properties to include in the response
INCLUDE: 
#LIMIT: Number of records to return (there is no pagination)
LIMIT: "2" 
#LOG_LEVEL: {OFF, INFO, or DEBUG}ruby
LOG_LEVEL: INFO 
