# Config
SPACE_URL: https://playground-travis-wiese.kinopsdev.io
SPACE_SLUG: SLUGHERE
SPACE_USERNAME: USERNAMEHERE
SPACE_PASSWORD: PWDHERE
KAPP_SLUG: KAPPSLUGHERE
FORM_SLUG: initial-checklist
LOG_LEVEL: info
FILTER: "values[Environment] = \"Production\""