SPACE_URL: https://<YOUR_SPACE>.kinops.io
SPACE_USERNAME: 
SPACE_PASSWORD: 
START: "2019-06-28T12:00:00Z" #Start time for paused trigger query
END: "2023-06-28T12:00:00Z" # End time for paused trigger query
LIMIT: "100" #Limit of records to return (there is no pagination)

